### ISSUE TITLE
TST04-Intégration continue

### ISSUE THREAD

**Issue by Flabbergabber** [Flabbergabber/pyalgotrade-opt#10]
- [ ] Comprendre l'utilisation de TravisCI.
- [ ] Configurer TravisCI pour exécuter la suite de tests ajoutées par #8.
- [ ] Configurer TravisCI pour effectuer le déploiement sur Amazon S3 via AWS CodeDeploy, décrit par #12.

**Comment by Flabbergabber** [comment]
- [ ] Configurer TravisCI pour exécuter la suite de tests ajoutées par #8
